### ISSUE TITLE
报错 java.lang.OutOfMemoryError: Failed to allocate a 36204 byte allocation with 8384 free bytes and 8KB until OOM

### ISSUE THREAD

**Issue by Destiny01** [jeasonlzy/OkHttpUtils#59]
报这个错误如下图：
![qq 20160918105108](https://cloud.githubusercontent.com/assets/11342391/18612503/e4b31028-7d8d-11e6-9096-7570b94ef8c5.png)
使用的缓存模式是：CacheMode.IF_NONE_CACHE_REQUEST

**Comment by jeasonlzy0216** [comment]
这个和缓存模式没有关系。异常发生在你的类里面。。详细的问题需要看你的代码还有抓个包看看服务器的数据。。
