### ISSUE TITLE
上传文件问题

### ISSUE THREAD

**Issue by xj999** [jeasonlzy/OkHttpUtils#60]
我的业务限制只能上传2M以下的图片,但是我不想在客户端写死这个数字,所以我们放在服务端来控制图片大小.当上传的图片大于2M 服务端直接返回 "XXXXX"提示语,目前我碰到的问题是,程序会等upProgress的progress到1.0 才给出提示   请问有什么办法让程序在服务端返回数据的当时就抛出信息 而不是等上传成功后才抛出

**Comment by jeasonlzy** [comment]
QQ交流群中已解决，原因是服务端虽然判断了文件大小，但是是在文件接受完毕后才判断的，并没有在超过文件大小后中断连接，所以客户端会一直上传。。服务端修改逻辑即可满足要求。
